version: '3.9'
services:
  # redis: 
  #   container_name: Redis
  #   image: redis:7.0.10
  #   restart: unless-stopped
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - redis:/data/db
  mysql:
    container_name: MySQL
    image: mysql/mysql-server
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql:/data/db
  node:
    container_name: node
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      DB_HOST: mysql
    depends_on:
      - mysql
volumes:
  mysql:
  redis: